### ISSUE TITLE
Plugin Won't Install - Coda 2.5.12 and El Capitan 10.11

### ISSUE THREAD

**Issue by brandonmhp** [emmetio/Emmet.codaplugin#26] opened 2015-10-02 15:29 UTC
Plugin opens Coda 2 but does not show in plug-ins or add menu items.

**Comment by gomesufuran** [comment] 2015-10-07 10:48
Same problem, coda move the plugin to disabled plugins folder, moving it manually doesn't work.

**Comment by joshsmith01** [comment] 2015-10-07 15:25
I love Coda 2 but the support from Panic and the plugin developers have left me stranded. This plugin has languished for over a year. It is particularly frustrating to see other editors with emmet support built-in. We've made hacks to "kind of" get it to work. I am at the point now that I can't afford to devote anymore time to it. I love Coda, I really do, I simply can't hobble over the finish line with it in tow anymore.

**Comment by oisauro** [comment] 2015-10-11 20:01
Hey guys, try [this one](https://github.com/emmetio/Emmet.codaplugin/issues/18#issuecomment-65317008).

**Comment by gomesufuran** [comment] 2015-10-11 20:42
works for me! thank you!

**Comment by donaldcampanjr** [comment] 2015-11-10 19:17
.. https://library.panic.com/coda/emmet-plugin/

i have:

- el Capitan 10.11.1
- coda 2.5.3

- so when i go to load Emmet plugin, it crashes Coda to the point that you cannot even open coda at all afterwards, you MUST uninstall and start over... .. .   .   .        .  ..

- i wish i wish i wish !!!

:D

**Comment by rvarga4** [comment] 2016-01-11 19:02
@oisauro worked for me as well thanks!

**Comment by leowebdev** [comment] 2016-01-12 04:08
worked! tks. @oisauro

**Comment by KaylashSingh** [comment] 2016-03-08 17:59
@oisauro worked for me, great!!!

**Comment by ryansigg** [comment] 2016-04-13 16:05
me too, still working in Coda 2.5.6, thanks @oisauro

**Comment by luxlogica** [comment] 2016-04-14 21:59
For those searching, the version kindly pointed to by @oisauro 6 months ago is now also buggy, and requires patches to work with the latest Coda in El Capitan. Currently, the only 'workable' version is an *unofficial* plugin, which already includes the latest patches, and which can be found here:

https://github.com/iemadk/emmet-coda-plugin

Note that there is still a nagging issue with that version: expanding your Emmet text by hitting 'tab' instead of 'command-e' will create an extra tab character in the text. It's *very* annoying.

It's sad that Panic won't lend a hand, specially considering how popular Emmet is as an extension in Sublime, Atom and others - over a million downloads in Sublime. Like @joshsmith01 above, I'm also thinking of switching to one of Coda's competitors because of this...

**Comment by sergeche** [comment] 2016-05-20 09:53
Just released new Emmet version for Coda: http://emmet.io/download/coda/

**Comment by sergeche** [comment] 2016-05-20 09:54
Duplicate of #23

**Closed by sergeche** 2016-05-20 09:54 UTC
