### ISSUE TITLE
Incompatible with Coda 2.5.4 and Yosemite 10.10.3.

### ISSUE THREAD

**Issue by Arcrammer** [emmetio/Emmet.codaplugin#25] opened 2015-04-13 16:58 UTC

**Comment by amityweb** [comment] 2015-05-03 09:08
Yeah, I installed this and nothing happens

**Comment by Arcrammer** [comment] 2015-05-03 15:47
It's a darned shame because this is a remarkable plug-in, but I don't want to use Sublime Text for it...

**Comment by jeff-swearingen** [comment] 2015-05-20 04:35
Hey guys,

If you haven't seen it already, this thread may have the answer you're looking for:

https://github.com/emmetio/Emmet.codaplugin/issues/18#issuecomment-64986379

Hope it helps.

**Comment by sergeche** [comment] 2016-05-20 09:55
Just released new Emmet version for Coda: http://emmet.io/download/coda/
Duplicate of #23

**Closed by sergeche** 2016-05-20 09:55 UTC
