### ISSUE TITLE
Latests Coda 2 ß Crash on launch if Emmet plugin enable

### ISSUE THREAD

**Issue by clawfire** [emmetio/Emmet.codaplugin#18] opened 2014-06-26 07:28 UTC
I just install the latest Coda 2 ß and can't launch it. It crash. After taking a look on the crash file, I see it's the Emmet plugin.

You can find the crash log file [here](http://s.thibau.lt/WH7I) and a bug report on the Coda 2 public tracker [here](https://hive.panic.com/issues/24702)

**Comment by impressbrand** [comment] 2015-01-13 11:16
Hi guys. I have the plugin working in Coda 2.5 in on Yosemite now. However the expansion is not being separated over line breaks. For example, when I type div.hello>ul>li*3 I get the following:

```
<div class="hello"><ul><li></li><li></li><li></li><li></li><li></li><li></li></ul></div>
```

...when I would expect:

```
<div class="hello">
   <ul>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
   </ul>
</div>
```

Can you please tell me where I'm going wrong? The preferences seem to be set correctly - see screenshot here:

![screen shot 2015-01-13 at 11 15 32](https://cloud.githubusercontent.com/assets/4630856/5719960/86d4f824-9b15-11e4-8730-ea6d8e640fb9.png)

**Comment by timkirtley** [comment] 2015-01-15 15:31
I have the same issue as described above by @impressbrand - my expanded elements all appear on one line.  I'm sure I also used to get the text cursor positioned correctly within expanded elements, whereas now its just positioned at the end. ie:

Cursor now at end:

`<p></p>|`

Used to be within element:

`<p>|</p>`

**Comment by atwixtor** [comment] 2015-01-15 15:34
I also have the same exact issue as @timkirtley and @impressbrand - not a deal-breaker, but a bit inconvenient.

**Comment by impressbrand** [comment] 2015-01-15 15:48
Thanks @timkirtley and @atwixtor for the updates - pleased in one way that it's not just me. I am also used to having the cursor correctly positioned on expansion. 

Would be interested to know if some are able to use the app with correct indented expansion, or if this is a universal issue?

Hope that someone is able to help - perhaps @nodequery ?

Best wishes, Andrew.

**Comment by wethecode** [comment] 2015-01-15 18:03
@impressbrand @atwixtor @timkirtley Check out my previous comment here: https://github.com/emmetio/Emmet.codaplugin/issues/18#issuecomment-64986379
It may help you.

**Comment by timgavin** [comment] 2015-01-15 18:10
@wethecode Worked for me, thanks!

**Comment by atwixtor** [comment] 2015-01-15 18:23
@wethecode Copied the suggested edits to the snippets file in and quit + reopened Coda and nothing changed - everything is still on 1 line and the cursor is being placed outside after expanding. I switched syntax modes a few times in my .php document, but no joy.

It DOES work when I'm in a .html file though...

Should the PHP format be showing up in this list after your suggested edits? Do we also need to set the "profile" in the snippets addition to "html" as well?

![screen shot 2015-01-15 at 1 19 14 pm](https://cloud.githubusercontent.com/assets/688435/5763587/9de2d432-9cb9-11e4-829c-f8ed54a68039.png)

**Comment by timkirtley** [comment] 2015-01-16 10:14
Replaced the contents of the snippets.json file, as per @wethecode comment, and expanding elements works properly now in terms of indenting and cursor position.

**Comment by atwixtor** [comment] 2015-01-16 14:16
@timkirtley everything works fine when expanding HTML in a .PHP document for you?

**Comment by timkirtley** [comment] 2015-01-16 14:19
Yes, in Coda the 'Syntax Mode' is set to 'PHP-HTML' and after updating the settings.json file inside the Emmet package folder it works correctly.

**Comment by atwixtor** [comment] 2015-01-16 14:39
I finally just replaced the snippets.json file with @wethecode 's gist/file, and Emmet suddenly started working as expected for line-breaks and indents. Perhaps I had other issues with my version of the .json file.

So in summary, using @nodequery 's updated plugin from https://github.com/emmetio/Emmet.codaplugin/issues/18#issuecomment-65317008 and the snippets.json file from https://gist.github.com/wethecode/1f79baf168680afb0f2d got Emmet working normally (as far as I can tell) again in Coda 2.5ß on Mavericks.

Thanks all!

**Comment by currentcreative** [comment] 2015-02-17 21:36
How do you edit snippets.json? Where is it, even? I read the above, but this knowledge is assumed known.

**Comment by davorpeic** [comment] 2015-02-22 18:22
@currentcreative Just found it myself so will share for future
/library/Application Support/Coda 2/Plugins/emmet.codaplugin (right click show package contents)/ Content/Recources/snippets.json

dp

**Comment by currentcreative** [comment] 2015-02-22 23:43
@davorpeic awesome, thank you!

**Comment by lvidal** [comment] 2015-02-25 22:52
Emmet doesn't recognize CSS properties under the the <style> tag in a .html file. Don't know if it is a bug or I am missing some setting.

**Comment by iemadk** [comment] 2015-04-11 07:40
@wethecode
@nodequery 

created a new repo for your fix and uploaded it

https://github.com/iemadk/emmet-coda-plugin

Thank you guys !

**Comment by FROLoff** [comment] 2015-04-13 12:03
After Coda update to 2.5.8 Emmet adds some spaces to the end of line after expanded abbreviation :(

**Comment by kct3937** [comment] 2015-06-20 16:53
Read all the comments, installed the plugin from Oct 20, and update snippets.json...Still no joy!
For various reasons I am still running Mtn Lion (10.8.5) and Coda 2.5.7.  Not seeing the plugin menu and expand abbreviation not working worth a s**t.  IMHO, Coda without emmet is like a day without sunshine...or Anita Bryant..

As strange as it is for all my years programming, I hardly use Git...so not entirely sure how to install the fix referenced by iemadk on Apr 11.
Almost wishing that I hadn't upgraded to version 2.  Really making me think about Sublime Text.

Any help, greatly appreciated.

**Comment by SergioJValentin** [comment] 2015-07-18 10:12
Thanks to everyone on this post who contributed.  I made the changes and it works for me!

**Comment by marktripney** [comment] 2015-07-19 15:56
Does anyone know why Emmet is putting spaces between tags?

In other words, I hit TAB to autocomplete a tag, and I have an unwanted space between them. For example, autocompleting 'p' results in:

<p> </p>

I want to remove that space!

**Comment by marktripney** [comment] 2015-07-19 15:58
Does anyone know how to remove unwanted spaces in Emmet autocomplete? For example, I hit TAB to autocomplete 'p' and I get...

`<p> </p>`

Any help greatly appreciated. It's a small thing, but it's driving me round the bend.

**Comment by augustoms** [comment] 2015-07-20 17:53
@marktripney , this is happening here too. And it's not just a space, is a 'tab space'..

Unfortunately, I don't know how to resolve it...
Any thoughts will be appreciated :)

**Comment by wivermarques** [comment] 2015-07-31 14:54
Same problem here, click on tab and it generates an extra space

**Comment by danielmee** [comment] 2015-12-05 15:08
I'm getting the unwanted tab space too. ie: `div>h1[tab]` produces:
```
<div>
	<h1>	</h1>
</div>
```
I also notice that, post expansion, the cursor position/selected text isn't always quite right... ie `![tab]`
<img width="175" alt="emmethighlight" src="https://cloud.githubusercontent.com/assets/1150775/11608461/b9b11f70-9bb9-11e5-8a4c-3cf29f46981a.png">
I wonder if it's ever going to make it's way back to 100% reliable? @cabel @nodequery

**Comment by Aminta** [comment] 2015-12-12 17:51
Hi, same problems here! There is a fix/workaround?


Thanks!

**Comment by mochimochipochi** [comment] 2016-01-03 13:48
I'm a bit late to the party, but after installing the plugin provided by @iemadk I too had the tab-space problem. Just as an fyi though, It seems that if you turn off the tab-completion and just use the default ctrl-k shortcut to expand that no tab is inserted. (So if I were to guess, it seems to me that the tab press is registered but also added as an input in the expanded text somehow...)

**Comment by webjac** [comment] 2016-02-26 17:54
I just wounded up here today and I'm going to make a recap for everyone visiting and not wanting to read it all.

Mr. @nodequery fixed the plugin, however, line breaks were not working. @iemadk did a fix but it produces an unwanted tab space if you hit tab to expand your Emmet text.

This is not fixed it yet. I hope that it'll get done eventually.

You can download the lateste working version of the Emmet plugin from here: https://github.com/iemadk/emmet-coda-plugin (thanks to @nodequery and @iemadk)

It works (with the unwanted tab space) on 2.5.16 and OSX El Capitan as of Feb 26th, 2016.

**Comment by sergeche** [comment] 2016-05-20 09:56
Just released new Emmet version for Coda: http://emmet.io/download/coda/
Duplicate of #23

**Closed by sergeche** 2016-05-20 09:56 UTC

**Comment by ddlong478** [comment] 2020-04-14 23:25
Hello, any one can help me out why this had been happened after I installed EmmetCoda 1.0.4 plugin  with Coda 2 version, 2.7.5. The behavior is really strange.

For example: 

<img width="362" alt="Screen Shot 2020-04-14 at 7 13 16 PM" src="https://user-images.githubusercontent.com/35847700/79282755-00a7c800-7e84-11ea-8241-3e96f4372073.png">

Then it showed after I use "tab" to make this look like below . . .

<img width="368" alt="Screen Shot 2020-04-14 at 7 13 50 PM" src="https://user-images.githubusercontent.com/35847700/79282791-14532e80-7e84-11ea-8b95-2c1418eb6936.png">

Eh? what is this?! 

It suppose to be &#60;div&#62;&#60;/div&#62;, not display: block.

Is this normal expand abbreviation? Let me know. Thanks!

**Comment by ardelmedia** [comment] 2020-04-14 23:26
-- Please reply above this line --

Thanks so much for contacting Ardel Media. 

We're not usually around at this time of day, but you can expect us
to get back to you during normal office hours. This reply is just to
let you know that your message has arrived safely in our inbox and
we'll be with you soon. 

Thank you! 

Ardel Media Ltd.

Ardel Media Limited is a company registered in England (company
number 09518001).
Registered address:  Ardel Media Ltd, c/o Switch Accountants, Unit
21, City West Business Park, Meadowfield, Co Durham, DH7 8ER, England.

--- End of message.

**Comment by ddlong478** [comment] 2020-04-14 23:38
> Hello, any one can help me out why this had been happened after I installed EmmetCoda 1.0.4 plugin with Coda 2 version, 2.7.5. The behavior is really strange.
> 
> For example:
> 
> <img alt="Screen Shot 2020-04-14 at 7 13 16 PM" width="362" src="https://user-images.githubusercontent.com/35847700/79282755-00a7c800-7e84-11ea-8241-3e96f4372073.png">
> 
> Then it showed after I use "tab" to make this look like below . . .
> 
> <img alt="Screen Shot 2020-04-14 at 7 13 50 PM" width="368" src="https://user-images.githubusercontent.com/35847700/79282791-14532e80-7e84-11ea-8b95-2c1418eb6936.png">
> 
> Eh? what is this?!
> 
> It suppose to be <div></div>, not display: block.
> 
> Is this normal expand abbreviation? Let me know. Thanks!

I decided to do it myself and uninstall it then quit the application and start fresh then install again to obtain the plugin I need, and boom it works well.

Sorry, my being panic without thinking for a while. It taught me to learn hard lesson to wait and think through before I jumped into the help wagon!! Tsk tsk myself!!

Although, Thanks for "reading" from me. Have a nice night and be Safe!
