### ISSUE TITLE
Cannot use plugin (Coda 2.5.5)

### ISSUE THREAD

**Issue by kimboender** [emmetio/Emmet.codaplugin#24] opened 2015-02-18 07:41 UTC
Hi there, 

I wanted to use Emmet for the first time and installed it like described here on Github. When i renamed the folder en doubleclicked on the plugin, it opens Coda but it will not appear in the plugins-list in coda prefereces. Therefore i can't activate it. Can anybody help me with this?

**Comment by asecondwill** [comment] 2015-02-22 05:24
+1

**Comment by davorpeic** [comment] 2015-02-22 18:11
check my answer
https://github.com/emmetio/Emmet.codaplugin/issues/23#issuecomment-60497593

Using that version on coda 2.5.6 on Mavericks

cheers

**Comment by eikeco** [comment] 2015-03-07 20:36
I have the same issue. @davorpeic's solution worked for me.

Yosemite 10.10.2
Coda 2.5.7

**Comment by pdemaria** [comment] 2015-04-10 18:41
I had this running with @davorpeic's version, but I couldn't keep it, Coda would still crash all the time... I'll try it again because I can't live without it, but I can't live with Coda crashing all the time either...

Yosemite 10.10.3
Coda 2.5.8

**Comment by pdemaria** [comment] 2015-04-23 11:54
Still crashes... @davorpeic the issues seems to be with using the shortcut key for **Wrap with Abbreviation**... I can do about 4 or 5 and then Coda hangs and crashes... I've also had it happen with expanding tags if I have a lot of them... I get a little farther.

Let me know if I can post anything that might help pin down the issue. This is driving me insane.

Yosemite 10.10.3
Coda 2.5.8

**Comment by sergeche** [comment] 2016-05-20 09:54
Just released new Emmet version for Coda: http://emmet.io/download/coda/
Duplicate of #23

**Closed by sergeche** 2016-05-20 09:54 UTC

**Comment by pdemaria** [comment] 2016-05-20 11:44
Yes! You have no idea how badly I've been missing Emmet.. I nearly switched
to Sublime Text but Coda was just too comfortable... Happy to go pro for
all the time this plugin saves me. Thank you! 🙌🏽

On Fri, May 20, 2016 at 5:54 AM, Sergey Chikuyonok <notifications@github.com

> wrote:
> 
> Just released new Emmet version for Coda: http://emmet.io/download/coda/
> Duplicate of #23 https://github.com/emmetio/Emmet.codaplugin/issues/23
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/emmetio/Emmet.codaplugin/issues/24#issuecomment-220564715

## 

Peter, at _Bluetone Media_

email / peter@bluetonemedia.com
