### ISSUE TITLE
Emmet plugin causes Coda to crash on launch on Yosemite

### ISSUE THREAD

**Issue by rcrooks** [emmetio/Emmet.codaplugin#22] opened 2014-10-04 20:41 UTC
Not sure what's doing it, but it's consistent, and as soon as I uninstalled the Emmet plugin, the problem went away. What a pity, as Emmet is the greatest tool in my HTML box -- forced me to switch from Coda to Sublime Text for the time being.

**Comment by MrAlexWeber** [comment] 2015-02-13 01:10
Props again to @FROLoff! ❤

**Comment by FROLoff** [comment] 2015-02-13 03:56
Here https://github.com/emmetio/Emmet.codaplugin/issues/18#issuecomment-65317008 more stable version of plugin by @nodequery — it works fine with the best ever feature "Wrap With Abbreviation". But "Update Image Size" still doesn't work.

**Comment by sergeche** [comment] 2016-05-20 09:55
Just released new Emmet version for Coda: http://emmet.io/download/coda/
Duplicate of #23

**Closed by sergeche** 2016-05-20 09:55 UTC
