### ISSUE TITLE
Plugin causes crashes in Coda 2.0.12

### ISSUE THREAD

**Issue by CinKon** [emmetio/Emmet.codaplugin#16] opened 2014-01-10 10:21 UTC
Unfortunately (i love emmet), the Coda-Plugin causes Coda to crash, when I indent multiple lines of code via Tab by pressing Tab ca. 5-6 times quickly in a row.

**Comment by sergeche** [comment] 2016-05-20 09:56
Just released new Emmet version for Coda: http://emmet.io/download/coda/
Duplicate of #23

**Closed by sergeche** 2016-05-20 09:56 UTC
